configM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from login.views import index,login,logout,adduser,user,deleteuser,edituser,searchuser
import repoM
import projectM
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',index),
    url(r'^user',user),
    url(r'^login/',login),
    url(r'^logout/',logout),
    url(r'^adduser/',adduser,name='adduser'),
    url(r'^edituser/([0-9]+)/$',edituser,name='edituser'),
    url(r'^deleteuser/([0-9]+)/$',deleteuser,name='deleteuser'),
    url(r'^searchuser/',searchuser,name='searchuser'),
    url(r'^captcha',include('captcha.urls')),
    url(r'^repoM/',include('repoM.urls')),
    url(r'^projectM/',include('projectM.urls')),
]

repoM/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^systemconfig', views.systemconfig, name='systemconfig'),
    url(r'^editsystemconfig/([0-9]+)/$',views.editsystemconfig, name='editsystemconfig'),
    url(r'^delsystemconfig/([0-9]+)/$',views.delsystemconfig, name='delsystemconfig'),
    url(r'^addsystemconfig',views.addsystemconfig, name='addsystemconfig'),
    url(r'^repo', views.repo, name='repo'),
    url(r'^addrepo', views.addrepo, name='addrepo'),
    url(r'^searchrepo', views.searchrepo, name='searchrepo'),  
    url(r'^importrepo', views.importrepo, name='importrepo'),
]

login/models.py
from django.db import models

# Create your models here.

class User(models.Model):

    gender =(
        ('male','男'),
        ('female','女'),
    )
    
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=30,unique=True)
    fullname = models.CharField(max_length=30)
    password = models.CharField(max_length=20)
    sex = models.CharField(max_length=20,choices=gender, default='男')
    email = models.EmailField(max_length=120,default="chuanxiao.li@jieshunpay.cn")
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username
    
    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = '用户'

repoM/models.py
from django.db import models
#Create your models here.
class SystemConfig(models.Model):
    SYS_Type = (
        ('git','Git 源码管理系统'),
        ('svn','SVN 源码管理系统'),
        ('jenkins','Jenkins 构建服务'),
        ('nexus','Nexus 依赖管理系统'),
        ('others','其他项目管理系统'),
    )
    sys_name = models.CharField(max_length=20,unique=True)
    sys_url = models.URLField()
    sys_api_url = models.URLField(null=True,blank=True)
    sys_username = models.CharField(max_length=128)
    sys_password = models.CharField(max_length=128)
    sys_privatetoken = models.CharField(max_length=50,null=True,blank=True)
    sys_version = models.CharField(max_length=20)
    sys_description = models.TextField(max_length=200)
    sys_type = models.CharField(max_length=20,choices=SYS_Type)
    sys_lable = models.CharField(max_length=20,null=True,blank=True)
    c_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.sys_url
    
    class Meta:
        ordering = ['-c_time']

class DeployHost(models.Model):
    host = models.GenericIPAddressField()
    host_username = models.CharField(max_length=30)
    host_password = models.CharField(max_length=30)
    host_port = models.IntegerField(default=22)
    host_description = models.TextField()
    c_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.host
    
    class Meta:
        ordering = ['-c_time']


class CodeRepo(models.Model):
    repo_name = models.CharField(max_length=128)
    repo_group = models.CharField(max_length=123)
    repo_url = models.URLField()
    repo_description = models.TextField()
    repo_system = models.IntegerField()
    repo_id = models.IntegerField()

    def __str__(self):
        return self.repo_name    
    
    class Meta:
        ordering = ['-repo_group']
        

login/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import User
from .form import UserForm,RegisterForm

# Create your views here.

def get_user(username,pwd):
    try:
        user_obj = User.objects.get(username=username)
    except:
        return (False, "用户不存在")
    if pwd != user_obj.password:
        print("密码不正确")
        return (False, "密码不正确")
    print("succeed!")
    return (True, "验证成功")

def index(request):
    userlist = User.objects.all()
    return render(request, 'index.html', {"userlist":userlist})



def login(request):
    message = None
    if request.session.get('is_login', None):
        return redirect('/index/')
    if request.method == 'POST':
        login_form = UserForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user_confirm,message = get_user(username,password)
            if user_confirm:
                request.session['is_login'] = True
                request.session['username'] = username
                return redirect('/index/')
            return render(request,'login.html',locals())
    login_form = UserForm()
    return render(request, 'login.html',locals())

def logout(request):
    request.session.flush()
    return redirect('/login/')


def adduser(request):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data['username']
            fullname = register_form.cleaned_data['fullname']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            try:
                user_obj =  User.objects.get(username=username)
                message = "用户已存在"
                return render(request,'adduser.html',locals())
            except:
                if password1 != password2:
                    message = "密码不一致"
                    return render(request,'adduser.html',locals())
                User.objects.create(username=username,fullname=fullname,password=password1,email=email,sex=sex)
                return redirect('/user/')
    register_form = RegisterForm()
    return render(request,'adduser.html', locals())


def user(request):
    userlist = User.objects.all()
    if request.method == 'POST':
        pass
    return render(request,'user.html',locals())


def deleteuser(request,user_id):
    User.objects.get(id=user_id).delete()
    return redirect('/user/')

def edituser(request,user_id):
    userinfo = User.objects.filter(id=user_id).values()[0]
    if request.method == 'POST':
        editinfo = request.POST.dict()
        if editinfo['password1'] != editinfo['password2']:
            message = "密码不一致"
            return render(request,'edituser.html',locals())
        User.objects.filter(id=user_id).update(username=editinfo['username'],fullname=editinfo['fullname'],password=editinfo['password1'],email=editinfo['email'],sex=editinfo['sex'])
        return redirect('/user/') 
    return render(request,'edituser.html',locals())

def searchuser(request):
    if request.method == 'POST':
        user_search = request.POST.dict()['user_search_filter']
        userlist = User.objects.filter(username__icontains=user_search)
        if  not userlist:
           userlist = User.objects.filter(email__icontains=user_search) 
    return render(request,'user.html',locals())   

templates/addsystemconfig.html
{% extends 'base-edit.html' %}
{% load staticfiles %}
{% block title %}添加配置
{% endblock title %}
{% block css %}
{% endblock css %}
{% block page-header %}添加配置{% endblock %}
{% block main_content %}
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
          <form class='form-horizontal' action="/repoM/addsystemconfig/" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

              {% csrf_token %}
                <div class="form-group">
                <label for="sys_name" class="col-md-3 control-label">系统名称：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="sys_name" name="sys_name"  placeholder="系统唯一标识">      
                </div>
                </div>
                <div class="form-group">
                <label for="sys_url" class="col-md-3 control-label">系统地址：</label>
                <div class="col-md-9">
                <input type="url" class="form-control" id="sys_url" name="sys_url">      
                </div>
                </div>
                <div class="form-group">
                <label for="sys_api_url" class="col-md-3 control-label">API 地址：</label>
                <div class="col-md-9">
                <input type="url" class="form-control" id="sys_api_url" name="sys_api_url" >  
                </div>
                </div>
              <div class="form-group">
                <label for="sys_username" class="col-md-3 control-label">系统用户名：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="sys_username"  name="sys_username">  
                </div>
              </div>
              <div class="form-group">
                <label for="sys_password" class="col-md-3 control-label">密码：</label>
                <div class="col-md-9">
                <input type="password" class="form-control" id="sys_password"  name="sys_password">  
                </div>
              </div>
              <div class="form-group">
                <label for="sys_privatetoken" class="col-md-3 control-label">系统 TOKEN：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="sys_privatetoken"  name="sys_privatetoken">  
                </div>
              </div>
              <div class="form-group">
                <label for="sys_version" class="col-md-3 control-label">系统版本：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="sys_version"  name="sys_version">  
                </div>
              </div>
                <div class="form-group">
                <label for="sys_lable" class="col-md-3 control-label">系统标签：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="sys_lable" name="sys_lable" placeholder="以逗号分隔，例如 git,gitlab">  
                </div>
              </div>
              <div class="form-group">
                <label for="sys_description" class="col-md-3 control-label">系统描述：</label>
                <div class="col-md-9">
                <textarea class="form-control" rows="3" id="sys_description" name="sys_description"></textarea>  
                </div>
              </div>
              <div class="form-group">
              <label for="sys_type" class="col-md-3 control-label">系统类型：</label>
                <div class="col-md-9">
               <select class="form-control" name='sys_type' >
                    <option value='git'>Git 源码管理系统</option>
                     <option value='svn'>SVN 源码管理系统</option>
                     <option value='jenkins'>Jenkins 构建服务</option>
                     <option value='nexus'>Nexus 依赖管理系统</option>
                     <option value='others'>其他项目管理系统</option>
                </select>
              </div>
            </div>
          
            <div class="col-md-9 col-md-offset-3">
              <button type="submit" class="btn btn-primary pull-right btn-block">提交</button>
           </div>

          </form>
        </div>
    </div> 
    
{% endblock main_content %}

templates/adduser.html
{% extends 'base-edit.html' %}
{% load staticfiles %}
{% block title %}添加用户
{% endblock title %}
{% block css %}
{% endblock css %}
{% block page-header %}添加用户{% endblock %}
{% block main_content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="/adduser/" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

              {% csrf_token %}

              <div class="form-group">
                  {{ register_form.username.label_tag }}
                  {{ register_form.username}}
              </div>
              <div class="form-group">
                  {{ register_form.fullname.label_tag }}
                  {{ register_form.fullname}}
              </div>
              <div class="form-group">
                  {{ register_form.password1.label_tag }}
                  {{ register_form.password1 }}
              </div>
              <div class="form-group">
                  {{ register_form.password2.label_tag }}
                  {{ register_form.password2 }}
              </div>
              <div class="form-group">
                  {{ register_form.email.label_tag }}
                  {{ register_form.email }}
              </div>
              <div class="form-group">
                  {{ register_form.sex.label_tag }}
                  {{ register_form.sex }}
              </div>
              <div class="form-group">
                  {{ register_form.captcha.errors }}
                  {{ register_form.captcha.label_tag }}
                  {{ register_form.captcha }}
              </div>

              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>

          </form>
        </div>
    </div> 
    
{% endblock main_content %}

templates/base-edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="{% static 'img/configM.ico' %}"  />
    <title>{% block title %}configM 系统{% endblock %}</title>

    <!-- Bootstrap core CSS -->
	<link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'img/configM.ico'%}" />
    <link rel="bookmark"href="{% static 'img/configM.ico'%}" />
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/index/">configM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/index/">Dashboard</a></li>
            <li><a href="/settings/">Settings</a></li>
            <li><a href="/logout/">logout</a></li>
            <li><a href="">Help</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{% block page-header %}Dashboard{% endblock %}</h3>
                </div>
            <div class="panel-body"> {% block main_content %}{% endblock %}</div>
            </div>      
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/base-login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'img/configM.ico' %}"  />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="bookmark" href="{% static 'img/configM.ico' %}" />
    {% block css %}{% endblock %}

  </head>
  <body>

    {% block content %}{% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    {% block js %}
    {% endblock js %}
  </body>
</html>

templates/base-nav.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="{% static 'img/configM.ico' %}"  />
    <title>{% block title %}configM 系统{% endblock %}</title>

    <!-- Bootstrap core CSS -->
	<link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
  {% block css %}
  {% endblock css %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'img/configM.ico'%}" />
    <link rel="bookmark"href="{% static 'img/configM.ico'%}" />
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/index/">configM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/index/">Dashboard</a></li>
            <li><a href="/settings/">Settings</a></li>
            <li><a href="/logout/">logout</a></li>
            <li><a href="">Help</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div>{% block main_content %}{% endblock %}</div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="{% static 'img/configM.ico' %}"  />
    <title>{% block title %}configM 系统{% endblock %}</title>

    <!-- Bootstrap core CSS -->
	<link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock css %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{% static 'img/configM.ico'%}" />
    <link rel="bookmark"href="{% static 'img/configM.ico'%}" />
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/index/">configM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/index/">Dashboard</a></li>
            <li><a href="/settings/">Settings</a></li>
            <li><a href="/logout/">logout</a></li>
            <li><a href="">Help</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar %}
          <ul class="nav nav-sidebar">
            <li class="{% block index_active %}{% endblock %}"><a href="/index/">首页 </a></li>
            <li class="{% block repo_active %}{% endblock %}"><a href="/repoM/repo/">仓库管理</a></li>
            <li class="{% block daily_submit_active %}{% endblock %}"><a href="/daily_submit/">每日提交</a></li>
            <li class="{% block code_statistics_active %}{% endblock %}"><a href="/code_statistics/">代码统计</a></li>
          </ul> 
          <ul class="nav nav-sidebar">
            <li class="{% block projects_active %}{% endblock %}"><a href="/projectM/project/">项目管理</a></li>
            <li class="{% block hosts_active %}{% endblock %}"><a href="/hosts/">服务器管理</a></li>
            <li class="{% block release_active %}{% endblock %}"><a href="/release/">发布管理</a></li>
            <li class="{% block auto_build_active %}{% endblock %}"><a href="/auto_build/">自动构建</a></li>

          </ul>
          <ul class="nav nav-sidebar">
            <li class="{% block user_active %}{% endblock %}"><a href="/user/">用户管理</a></li>
            <li class="{% block env_active %}{% endblock %}"><a href="/env/">环境管理</a></li>
            <li class="{% block systemconfig_active %}{% endblock %}"><a href="/repoM/systemconfig/">系统配置</a></li>
          </ul>
{% endblock sidebar %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">{% block page-header %}Dashboard{% endblock %}</h1>
		   {% block main_content %}{% endblock %}      
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}configM 主页
{% endblock title %}
{% block css %}
{% endblock css %}
{% block page-header %}用户清单{% endblock %}
{% block index_active %}active{% endblock %}
{% block main_content %}
    <table class="table">
    <thead>
        <tr>
            <th>用户名</th>
            <th>全名</th>
            <th>创建时间</th>
            <th>邮箱</th>
        </tr>
    </thead>
    <tbody>
        {% for  user in  userlist %}    
        <tr>
            <td>{{user.username}}</td>
            <td>{{user.fullname}}</td>
            <td>{{user.c_time}}</td>
            <td>{{user.email}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/login.html
{% extends 'base-login.html' %}
{% load staticfiles %}
{% block title %}登录
{% endblock title %}
{% block css %}
<link href="{% static 'css/login.css' %}" rel="stylesheet"/>
{% endblock css %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4 login-content">

          <form class='form-login' action="/login/" method="post">
            {% if message %}
            <div class="alert alert-warning">{{message}}</div>
            {% endif %}
              <h2 class="text-center">欢迎登录 configM</h2>
                  <div class="form-group">
                    {{ login_form.username.label_tag }}
                    {{ login_form.username}}
                  </div>
                  <div class="form-group">
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                  </div>
                <button type="submit" class="btn btn-success  btn-lg btn-block"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; 登录</button>
          </form>
    
        </div>
    </div> <!-- /container -->
{% endblock %}

templates/systemconfig.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}configM 系统配置
{% endblock title %}
{% block css %}
{% endblock css %}
{% block page-header %}系统配置{% endblock %}
{% block systemconfig_active %}active{% endblock %}
{% block main_content %}
<div class="container">
<div class="row">
     <form class="from"  action="/repoM/systemconfig/" method="post" >
        <a class="btn btn-primary col-md-2  " href="/repoM/addsystemconfig/" role="button">
        <span class="glyphicon glyphicon-cog" aria-hidden="true">
        </span>&nbsp;&nbsp;添加配置</a>
        <div class="form-group col-md-3 col-md-offset-5">
          <input type="text" class="form-control" name="config_search_filter" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-primary">查询</button>
    </form>     
    
</div>
</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">配置信息</div>

  <!-- Table -->
    <table class="table">
    <thead>
        <tr>
            <th>系统名称</th>
            <th>系统地址</th>
            <th>系统描述</th>
            <th>系统类型</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
    </thead>
    {% if systemconfig_obj %}
    <tbody>
        {% for  systemconfig in  systemconfig_obj %}    
        <tr>
            <td>{{systemconfig.sys_name}}</td>
            <td><a href="{{systemconfig.sys_url}}">{{systemconfig.sys_url}}</a></td>
            <td>{{systemconfig.sys_description}}</td>
            <td>{{systemconfig.get_sys_type_display}}</td>
            <td>{{systemconfig.c_time}}</td>
            <td>
                <a href="{% url 'editsystemconfig' systemconfig.id %}" class="btn btn-primary" role="button"><span class="glyphicon  glyphicon-pencil" aria-hidden="true"></span>&nbsp;编辑</a>
                <a href="{% url 'delsystemconfig' systemconfig.id %}" class="btn btn-danger" role="button"><span class="glyphicon  glyphicon-trash" aria-hidden="true"></span>&nbsp;删除</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
        {% else %}
        <tbody></tbody>
        <h2>没有数据</h2>
        {% endif %}
    </table>
</div>

{% endblock %}