configM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from login.views import index,login,logout,adduser,user,deleteuser,edituser,searchuser
import repoM
import projectM
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',index),
    url(r'^user',user),
    url(r'^login/',login),
    url(r'^logout/',logout),
    url(r'^adduser/',adduser,name='adduser'),
    url(r'^edituser/([0-9]+)/$',edituser,name='edituser'),
    url(r'^deleteuser/([0-9]+)/$',deleteuser,name='deleteuser'),
    url(r'^searchuser/',searchuser,name='searchuser'),
    url(r'^captcha',include('captcha.urls')),
    url(r'^repoM/',include('repoM.urls')),
    url(r'^projectM/',include('projectM.urls')),
]

repoM/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^systemconfig', views.systemconfig, name='systemconfig'),
    url(r'^editsystemconfig/([0-9]+)/$',views.editsystemconfig, name='editsystemconfig'),
    url(r'^delsystemconfig/([0-9]+)/$',views.delsystemconfig, name='delsystemconfig'),
    url(r'^addsystemconfig',views.addsystemconfig, name='addsystemconfig'),
    url(r'^repo', views.repo, name='repo'),
    url(r'^addrepo', views.addrepo, name='addrepo'),
    url(r'^searchrepo', views.searchrepo, name='searchrepo'),  
    url(r'^importrepo', views.importrepo, name='importrepo'),
]

projectM/models.py
from django.db import models
from repoM.models import CodeRepo,DeployHost
from login.models import User

# Create your models here.
class ProjectList(models.Model):
    pro_type = (
        ('standard','内部-标准项目'),
        ('Non-standard','内部-非标项目'),
        ('Outgoing','外部项目'),
    )
    project_name = models.CharField(max_length=128,unique=True)
    project_type = models.CharField(max_length=20,choices=pro_type,default='Internal')
    description = models.TextField()
    project_key = models.CharField(max_length=20,unique=True)
    code_repo = models.ManyToManyField(CodeRepo, through='ProjectRepo')
    c_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.project_name
    
    class Meta:
        ordering = ['-c_time']

class ProjectRepo(models.Model):
    ProjectList = models.ForeignKey(ProjectList,on_delete=models.PROTECT)
    CodeRepo = models.ForeignKey(CodeRepo,on_delete=models.PROTECT)
    branch_name = models.CharField(max_length=20,default='branch-dev')
    build_url = models.URLField(null=True)
    deploy_host = models.ForeignKey(DeployHost,on_delete=models.PROTECT)

class ProjectRelease(models.Model):
    ProjectList = models.ForeignKey(ProjectList,on_delete=models.PROTECT)
    c_time = models.DateField(auto_now_add=True)
    release_version = models.CharField(max_length=20)
    release_note = models.TextField()
    author = models.ForeignKey(User,on_delete=models.PROTECT)


class CodeRelease(models.Model):        
    Project_release = models.ForeignKey(ProjectRelease,on_delete=models.PROTECT)
    code_repo = models.ForeignKey(CodeRepo,on_delete=models.PROTECT)
    code_sha = models.CharField(max_length=50)
    release_time = models.DateField(auto_now_add=True)
    env = models.CharField(max_length=20)
    branch = models.CharField(max_length=50)

templates/project/addproject.html
{% extends '../base-edit.html' %}
{% load staticfiles %}
{% block title %}添加 project
{% endblock title %}
{% block css %}
{% endblock css %}
{% block page-header %}添加 project{% endblock %}
{% block main_content %}
    <div class="container">
        <div class="col-md-6 col-md-offset-3">
          <form class='form-horizontal' action="/projectM/addproject" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
                <div class="form-group">
                <label for="project_name" class="col-md-3 control-label">项目名称：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="project_name" name="project_name">      
                </div>
                </div>
                <div class="form-group">
                <label for="project_key" class="col-md-3 control-label">项目键值：</label>
                <div class="col-md-9">
                <input type="text" class="form-control" id="project_key" name="project_key" placeholder="所有字母将会转换为大写"  >      
                </div>
                </div>
              <div class="form-group">
                <label for="project_description" class="col-md-3 control-label">项目描述：</label>
                <div class="col-md-9">
                <textarea class="form-control" rows="3" id="project_description" name="project_description"></textarea>  
                </div>
              </div>
          <div class="form-group">
              <label for="project_type" class="col-md-3 control-label"><p>项目类型:</p></label>
                <div class="col-md-9">
                <select class="form-control" name='project_type' >
                <option value='standard'>内部-标准项目</option>
                <option value='Non-standard'>内部-非标项目</option>
                <option value='Outgoing'>外部项目</option>
                </select>
              </div>
            </div>
            <div class="col-md-9 col-md-offset-3">
              <button type="submit" class="btn btn-primary pull-right btn-block">提交</button>
           </div>

          </form>
        </div>
    </div> 
    
{% endblock main_content %}

templates/project/project.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}configM 项目管理
{% endblock title %}
{% block css %}
<link href="{% static 'css/repo.css' %}" rel="stylesheet"/>
{% endblock css %}
{% block page-header %}项目管理{% endblock %}
{% block projects_active %}active{% endblock %}
{% block main_content %}
<div class="container">

<div class="row">
     <form class="from"  action="/projectM/searchproject/" method="post" >
     <div class="button-margin">
        <a class="btn btn-primary btn-block " href="/projectM/addproject/" role="button">
        <span class="glyphicon glyphicon-cog " aria-hidden="true">
        </span>&nbsp;&nbsp;添加项目</a>
         </div>
        <div class="form-group col-md-3 col-md-offset-5">
          <input type="text" class="form-control" name="project_search_filter" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-primary">查询</button>
    </form>     
    
</div>
</div>

<div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">项目列表</div>

  <!-- Table -->
    <table class="table">
    <thead>
        <tr>
            <th>项目名称</th>
            <th>项目描述</th>
            <th>项目类型</th>
            <th>项目键值</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
    </thead>
    {% if projects %}
    <tbody>
        {% for  project in  projects %}    
        <tr>
            <td>{{project.project_name}}</td>
            <td>{{project.description}}</td>
            <td>{{project.get_project_type_display}}</td>
            <td><a href="{{project.project_key}}">{{project.project_key}}</a></td>
            <td>{{project.c_time}}</td>
               <td>
                <a href="#" class="btn btn-primary" role="button"><span class="glyphicon  glyphicon-pencil" aria-hidden="true"></span>&nbsp;编辑</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
        {% else %}
        <tbody>
        </tbody>
        <h2>没有数据</h2>
        {% endif %}
    </table>
</div>

{% endblock %}